/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-06-09 01:17:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.students;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<link rel =\"stylesheet\" href=\"../home.css\">\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("\t<title>학사관리 시스템</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"divPage\">\r\n");
      out.write("\t\t<div id=\"divTop\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../header.jsp", out, false);
      out.write("</div>\r\n");
      out.write("\t<div id=\"divCenter\">\r\n");
      out.write("\t\t<div id=\"divMenu\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../menu.jsp", out, false);
      out.write("</div>\r\n");
      out.write("\t\t<div id=\"divContent\">\r\n");
      out.write("\t\t\t<!-- 여기에 내용 등록 시작-->\r\n");
      out.write("\t\t\t<div id=\"divHeader\"><h2>학 생 목 록</h2></div>\r\n");
      out.write("\t\t\t<div id=\"divCondition\">\r\n");
      out.write("\t\t\t\t<div id=\"divSearch\">\r\n");
      out.write("\t\t\t\t\t<select id=\"selKey\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"scode\">학생번호</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"sname\">학생이름</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"dept\">학생학과</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"pname\">교수이름</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"txtWord\">\r\n");
      out.write("\t\t\t\t\t<select id=\"selperpage\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">3행</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"5\">5행</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"10\">10행</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" id=\"btnSearch\" value=\"검색\">\r\n");
      out.write("\t\t\t\t\t<span style=\"font-size:12px;\">검색수: <b id=\"count\"></b>건</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"divSort\">\r\n");
      out.write("\t\t\t\t\t<select id=\"selOrder\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"scode\">번호</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"sname\">이름</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"dept\">학과</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"pname\">교수이름</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t<select id=\"selDesc\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\">오름차순</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"desc\">내림차순</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<table id=\"tbl\"></table>\r\n");
      out.write("\t\t\t<script id=\"temp\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t\t\t\t<tr class=\"title\">\r\n");
      out.write("\t\t\t\t\t<td width=100>학생번호</td>\r\n");
      out.write("\t\t\t\t\t<td width=100>학생이름</td>\r\n");
      out.write("\t\t\t\t\t<td width=100>학생학과</td>\r\n");
      out.write("\t\t\t\t\t<td width=100>생년월일</td>\r\n");
      out.write("\t\t\t\t\t<td width=100>교수번호</td>\r\n");
      out.write("\t\t\t\t\t<td width=100>교수이름</td>\r\n");
      out.write("\t\t\t\t\t<td width=70>학생정보</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t{{#each array}}\r\n");
      out.write("\t\t\t\t<tr class=\"row\">\r\n");
      out.write("\t\t\t\t\t<td class=\"scode\">{{scode}}</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"sname\">{{sname}}</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"dept\">{{dept}}</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"birthday\">{{birthday}}</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"advisor\">{{advisor}}</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"pname\">{{pname}}</td>\r\n");
      out.write("\t\t\t\t\t<td><button>학생정보</button></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t{{/each}}\r\n");
      out.write(" \t\t\t</script>\r\n");
      out.write(" \t\t\t<div id=\"pagination\">\r\n");
      out.write(" \t\t\t\t<button id=\"btnPre\">◀</button> <button id=\"btnNext\">▶</button>\r\n");
      out.write("\t\t\t\t[<span id=\"curPage\"></span>/<span id=\"totPage\"></span>]\r\n");
      out.write(" \t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 여기에 내용 등록 종료-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"divBottom\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../footer.jsp", out, false);
      out.write("</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar url=\"/students/list\";\r\n");
      out.write("\t$(\"#tbl\").on(\"click\", \".row button\", function(){\r\n");
      out.write("\t\tvar scode=$(this).parent().parent().find(\".scode\").html();\r\n");
      out.write("\t\tlocation.href=\"read?scode=\" + scode;\r\n");
      out.write("\t})\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"../home.js\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
