/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-06-05 07:54:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.professors;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class read_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:substring", org.apache.taglibs.standard.functions.Functions.class, "substring", new Class[] {java.lang.String.class, int.class, int.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1589249478582L));
    _jspx_dependants.put("jar:file:/C:/data/jsp/0511/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/haksa/WEB-INF/lib/standard.jar!/META-INF/fn.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/C:/data/jsp/0511/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/haksa/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("   <meta charset=\"UTF-8\">\r\n");
      out.write("   <title>학사관리 시스템</title>\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"../home.css\">\r\n");
      out.write("   <script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div id=\"divPage\">\r\n");
      out.write("      <div id=\"divTop\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../header.jsp", out, false);
      out.write("</div>\r\n");
      out.write("      <div id=\"divCenter\">\r\n");
      out.write("         <div id=\"divMenu\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../menu.jsp", out, false);
      out.write("</div>\r\n");
      out.write("         <div id=\"divContent\">\r\n");
      out.write("         <!-- 여기에 출력 내용 시작 -->\r\n");
      out.write("         <div id=\"divHeader\"><h2>교 수 등 록</h2></div>\r\n");
      out.write("         <form name=\"frm\" action=\"update\" method=\"post\">\r\n");
      out.write("             <table>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td width=100 class=\"title\" width=150>교수번호</td>\r\n");
      out.write("                  <td width=100><input type=\"text\" name=\"pcode\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.pcode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" size=10 placeholder=\"교수번호\"></td>\r\n");
      out.write("                  <td width=100 class=\"title\" width=150>교수학과</td>\r\n");
      out.write("                  <td width=100>\r\n");
      out.write("                      <select name=\"dept\">\r\n");
      out.write("                     <option ");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write(">전산</option>\r\n");
      out.write("                     <option ");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write(">전자</option>\r\n");
      out.write("                     <option ");
      if (_jspx_meth_c_005fout_005f2(_jspx_page_context))
        return;
      out.write(">건축</option>\r\n");
      out.write("                   </select>\r\n");
      out.write("                   </td>\r\n");
      out.write("                  <td width=100 class=\"title\" width=150>임용일자</td>\r\n");
      out.write("                  <td>\r\n");
      out.write("                     <input type=\"text\" name=\"yy\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:substring(vo.hiredate,0,4)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\" maxlength=4 size=2 placeholder=\"yyyy\">년\r\n");
      out.write("                     <input type=\"text\" name=\"MM\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:substring(vo.hiredate,5,7)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\" maxlength=2 size=2 placeholder=\"MM\">월\r\n");
      out.write("                     <input type=\"text\" name=\"dd\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:substring(vo.hiredate,8,10)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\" maxlength=2 size=2 placeholder=\"dd\">일\r\n");
      out.write("                  </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td width=100 class=\"title\" width=150>교수이름</td>\r\n");
      out.write("                  <td width=100><input type=\"text\" name=\"pname\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.pname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" size=10 placeholder=\"교수이름\"></td>\r\n");
      out.write("                  <td width=100 class=\"title\" width=150>교수급여</td>\r\n");
      out.write("                  <td><input type=\"text\" name=\"salary\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.salary}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" maxlength=12 placeholder=\"급여\"></td>\r\n");
      out.write("                  <td width=100 class=\"title\" width=150>교수직급</td>\r\n");
      out.write("                  <td>\r\n");
      out.write("                     <input type=\"radio\" name=\"title\" value=\"정교수\" ");
      if (_jspx_meth_c_005fout_005f3(_jspx_page_context))
        return;
      out.write(">정교수\r\n");
      out.write("                     <input type=\"radio\" name=\"title\" value=\"부교수\" ");
      if (_jspx_meth_c_005fout_005f4(_jspx_page_context))
        return;
      out.write(">부교수\r\n");
      out.write("                     <input type=\"radio\" name=\"title\" value=\"조교수\" ");
      if (_jspx_meth_c_005fout_005f5(_jspx_page_context))
        return;
      out.write(">조교수\r\n");
      out.write("                  </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("             </table>\r\n");
      out.write("             <div id=\"pagination\">\r\n");
      out.write("                 <input type=\"submit\" value=\"저장\" >\r\n");
      out.write("                 <input type=\"button\" value=\"삭제\" id=\"btnDelete\">  \r\n");
      out.write("                 <input type=\"reset\" value=\"취소\">\r\n");
      out.write("              </div>\r\n");
      out.write("         </form>\r\n");
      out.write("         <div id=\"divHeader\"><h2>담 당 강 좌</h2></div>\r\n");
      out.write("         <table id=\"tbl\"></table>\r\n");
      out.write("\t\t\t<script id=\"temp\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t\t\t\t<tr class=\"title\">\r\n");
      out.write("\t\t\t\t\t<td width=100>강좌번호</td>\r\n");
      out.write("\t\t\t\t\t<td width=100>강좌이름</td>\r\n");
      out.write("\t\t\t\t\t<td width=80>강의실</td>\r\n");
      out.write("\t\t\t\t\t<td width=100>강의시수</td>\r\n");
      out.write("\t\t\t\t\t<td width=110>최대수강인원</td>\r\n");
      out.write("\t\t\t\t\t<td width=100>수강신청인원</td>\r\n");
      out.write("\t\t\t\t\t<td width=80>강좌정보</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t{{#each cArray}}\r\n");
      out.write("\t\t\t\t<tr class=\"row\">\r\n");
      out.write("\t\t\t\t\t<td class=\"lcode\">{{lcode}}</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"lname\">{{lname}}</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"room\">{{room}}</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"hours\">{{hours}}</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"capacity\">{{capacity}}</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"persons\">{{persons}}</td>\r\n");
      out.write("\t\t\t\t\t<td><button class=\"cButton\">강좌정보</button></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t{{/each}}\r\n");
      out.write(" \t\t\t</script>\r\n");
      out.write(" \t\t\t\r\n");
      out.write(" \t\t\t <div id=\"divHeader\"><h2>담 당 학 생</h2></div>\r\n");
      out.write("         <table id=\"tbl2\"></table>\r\n");
      out.write("\t\t\t<script id=\"temp2\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t\t\t\t<tr class=\"title\">\r\n");
      out.write("\t\t\t\t\t<td width=100>학생번호</td>\r\n");
      out.write("\t\t\t\t\t<td width=100>학생이름</td>\r\n");
      out.write("\t\t\t\t\t<td width=80>학과</td>\r\n");
      out.write("\t\t\t\t\t<td width=100>학년</td>\r\n");
      out.write("\t\t\t\t\t<td width=110>생년월일</td>\r\n");
      out.write("\t\t\t\t\t<td width=100>학생정보</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t{{#each sArray}}\r\n");
      out.write("\t\t\t\t<tr class=\"row\">\r\n");
      out.write("\t\t\t\t\t<td class=\"scode\">{{scode}}</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"sname\">{{sname}}</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"dept\">{{dept}}</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"year\">{{year}}</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"birthday\">{{birthday}}</td>\r\n");
      out.write("\t\t\t\t\t<td><button class=\"sButton\">학생정보</button></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t{{/each}}\r\n");
      out.write(" \t\t\t</script>\r\n");
      out.write("         <!-- 여기에 출력 내용 종료 -->\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"divBottom\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../footer.jsp", out, false);
      out.write("</div>\r\n");
      out.write("   </div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("   var pcode = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.pcode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("   var pname = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.pname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write(" \r\n");
      out.write("   getList();\r\n");
      out.write("   \r\n");
      out.write("   function getList(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\turl:\"/professors/cslist\",\r\n");
      out.write("\t\t\tdata:{\"pcode\":pcode},\r\n");
      out.write("\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tvar template = Handlebars.compile($(\"#temp\").html());\r\n");
      out.write("\t\t\t\t$(\"#tbl\").html(template(data));\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar template2 = Handlebars.compile($(\"#temp2\").html());\r\n");
      out.write("\t\t\t\t$(\"#tbl2\").html(template2(data));\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("   \r\n");
      out.write("   $(\"#tbl\").on(\"click\", \".row .cButton\", function(){\r\n");
      out.write("\t\tvar lcode=$(this).parent().parent().find(\".lcode\").html();\r\n");
      out.write("\t\tlocation.href=\"/courses/read?lcode=\"+lcode;\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#tbl2\").on(\"click\", \".row .sButton\", function(){\r\n");
      out.write("\t\tvar scode=$(this).parent().parent().find(\".scode\").html();\r\n");
      out.write("\t\tlocation.href=\"/students/read?scode=\"+scode;\r\n");
      out.write("\t})\r\n");
      out.write("   \r\n");
      out.write("   //삭제버튼 클릭\r\n");
      out.write("      $(\"#btnDelete\").on(\"click\",function(){\r\n");
      out.write("      if(!confirm(pcode + \"교수를 삭제하시겠습니까?\")) return;\r\n");
      out.write("          $.ajax({\r\n");
      out.write("             type:\"post\",\r\n");
      out.write("             url:\"/professors/delete\",\r\n");
      out.write("             data:{\"pcode\":pcode},\r\n");
      out.write("             dataType:\"json\",\r\n");
      out.write("             success:function(data){\r\n");
      out.write("                if(data.scount==0 && data.ccount==0){\r\n");
      out.write("                   alert(\"삭제되었습니다\");\r\n");
      out.write("                   location.href=\"/professors/list.jsp\";\r\n");
      out.write("                }else{\r\n");
      out.write("                   alert(\"지도학생: \" + data.scount + \" 담당과목: \" + data.ccount + \"이 있어 삭제할 수 없습니다.\");\r\n");
      out.write("                }\r\n");
      out.write("             }\r\n");
      out.write("          })\r\n");
      out.write("      });\r\n");
      out.write("   //코드 중복체크\r\n");
      out.write("   $(frm).submit(function(e){\r\n");
      out.write("      e.preventDefault();\r\n");
      out.write("      if(!confirm(pname +\"교수 정보를 수정하시겠습니까?\")) return;\r\n");
      out.write("      frm.submit();\r\n");
      out.write("   });\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent(null);
    // /professors/read.jsp(30,29) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.dept=='전산'?'selected':''}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f1.setParent(null);
    // /professors/read.jsp(31,29) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.dept=='전자'?'selected':''}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
    if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f2.setParent(null);
    // /professors/read.jsp(32,29) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.dept=='건축'?'selected':''}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
    if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f3.setParent(null);
    // /professors/read.jsp(49,66) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.title=='정교수'?'checked':''}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
    if (_jspx_th_c_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f4.setParent(null);
    // /professors/read.jsp(50,66) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.title=='부교수'?'checked':''}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f4 = _jspx_th_c_005fout_005f4.doStartTag();
    if (_jspx_th_c_005fout_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f5 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f5.setParent(null);
    // /professors/read.jsp(51,66) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f5.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.title=='조교수'?'checked':''}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f5 = _jspx_th_c_005fout_005f5.doStartTag();
    if (_jspx_th_c_005fout_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f5);
    return false;
  }
}
